name: Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Run Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file ./shopping/pom.xml
  build:
    needs: tests
    name: Build maven package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('./shopping/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build package war
        run: mvn -B package -DskipTests --file ./shopping/pom.xml
      - name: Upload .war
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./shopping/target/app.war